---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-kraft
  namespace: kafka
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kafka-kraft
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      namespace: kafka
    replicaCount: 1
    kafka:
      numPartitions: 1
      defaultReplicationFactor: 1
      offsetsTopicReplicationFactor: 1
      transactionStateLogReplicationFactor: 1
      transactionStateLogMinIsr: 1
      sharedCoordinatorTopicReplicationFactor: 1
      sharedCoodinatorStateTopicMinIsr: 1
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
         memory: 1Gi
         cpu: 500m
