---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka-kraft
  namespace: kafka-lab
spec:
  interval: 30m
  chart:
    spec:
      chart: kafka-kraft-sasl-ssl
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: jittakal-oci
        namespace: flux-system
      interval: 12h
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Add your kafka-kraft base configuration here
    # Example:
    # replicaCount: 1
    # resources:
    #   limits:
    #     memory: 2Gi
    #     cpu: 1000m
    #   requests:
    #     memory: 1Gi
    #     cpu: 500m