---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kafeventproducer
  namespace: kafka-producers
spec:
  interval: 24h
  url: oci://registry-1.docker.io/jittakal/kafeventproducerchart
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "1.x"
