---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kafluxgitops/infrastructure/configs
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: configs
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kafluxgitops/infrastructure/controllers
  prune: true
  wait: true
  timeout: 15m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platforms
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kafluxgitops/infrastructure/platforms
  prune: true
  wait: true
  timeout: 15m0s