{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka-kraft-sasl-ssl.fullname" . }}
  namespace: {{ include "kafka-kraft-sasl-ssl.namespace" . }}
  labels:
    {{- include "kafka-kraft-sasl-ssl.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-kraft-sasl-ssl.selectorLabels" . | nindent 6 }}
{{- end }}
