---
# Secret for keystore password
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-kraft-sasl-ssl.fullname" . }}-keystore-password
  namespace: {{ include "kafka-kraft-sasl-ssl.namespace" . }}
  labels:
    {{- include "kafka-kraft-sasl-ssl.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
type: Opaque
stringData:
  password: {{ .Values.certManager.keystorePassword | quote }}

---
# Secret for TLS credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-kraft-sasl-ssl.fullname" . }}-tls-credentials
  namespace: {{ include "kafka-kraft-sasl-ssl.namespace" . }}
  labels:
    {{- include "kafka-kraft-sasl-ssl.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
type: Opaque
stringData:
  keystore.cred: {{ .Values.certManager.keystorePassword | quote }}
  ssl-key.cred: {{ .Values.certManager.keystorePassword | quote }}
  truststore.cred: {{ .Values.certManager.keystorePassword | quote }}

---
# Secret for SASL JAAS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-kraft-sasl-ssl.fullname" . }}-sasl-jaas
  namespace: {{ include "kafka-kraft-sasl-ssl.namespace" . }}
  labels:
    {{- include "kafka-kraft-sasl-ssl.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
type: Opaque
stringData:
  kafka-server-jaas.config: |
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="{{ .Values.security.sasl.username }}"
      password="{{ .Values.security.sasl.password }}"
      user_{{ .Values.security.sasl.username }}="{{ .Values.security.sasl.password }}"
      {{- range .Values.security.sasl.users }}
      user_{{ .username }}="{{ .password }}"
      {{- end }};
    };

---
# Secret for client configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-kraft-sasl-ssl.fullname" . }}-client-config
  namespace: {{ include "kafka-kraft-sasl-ssl.namespace" . }}
  labels:
    {{- include "kafka-kraft-sasl-ssl.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
type: Opaque
stringData:
  client.properties: |
    # Security Protocol
    security.protocol=SASL_SSL
    
    # SASL Configuration
    sasl.mechanism={{ .Values.security.saslMechanism }}
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.security.sasl.username }}" \
      password="{{ .Values.security.sasl.password }}";
    
    # SSL Configuration
    ssl.truststore.type=PKCS12
    ssl.truststore.location=/etc/kafka/client/secrets/truststore.p12
    ssl.truststore.password={{ .Values.certManager.keystorePassword }}
    ssl.keystore.type=PKCS12
    ssl.keystore.location=/etc/kafka/client/secrets/keystore.p12
    ssl.keystore.password={{ .Values.certManager.keystorePassword }}
    ssl.key.password={{ .Values.certManager.keystorePassword }}
    ssl.endpoint.identification.algorithm={{ .Values.security.ssl.endpointIdentificationAlgorithm }}
    
    # Producer Configuration
    acks=all
    retries=3
    batch.size=16384
    linger.ms=10
    compression.type={{ .Values.kafka.compressionType }}
    
    # Consumer Configuration
    auto.offset.reset=earliest
    enable.auto.commit=true
    auto.commit.interval.ms=5000
